-- Pessoa 
INSERT INTO Pessoa VALUES(1, 'Hugo Guimaraes', '17-07-2000', '4490', 'Praca dos Combatentes');
INSERT INTO Pessoa VALUES(2, 'Samuel Fernandes', '28-06-2000', '4860', 'Rua Doutor Franscico Botelho');
INSERT INTO Pessoa VALUES(3, 'Paulo Ribeiro', '16-10-2000', '4490', 'Praca dos Combatentes');
INSERT INTO Pessoa VALUES(4, 'Pedro Nero ', '28-01-1969', '4490', 'Praca dos Combatentes');
INSERT INTO Pessoa VALUES(5, 'Ana Monteiro', '24-08-1969', '4490', 'Praca dos Combatentes');
INSERT INTO Pessoa VALUES(6, 'Marta Lopes', '12-01-2000', '4490', 'Avenida 25 de Abril');
INSERT INTO Pessoa VALUES(7, 'Marta Figueiredo', '30-01-2000', '4490', 'Rua 31 de Janeiro');
INSERT INTO Pessoa VALUES(8, 'Rodrigo Festas', '17-07-2000', '4490', 'Rua Caetano de Oliveira');
INSERT INTO Pessoa VALUES(9, 'Carlos Monteiro', '17-07-2000', '4490', 'Rua Doutor Leonardo Coimbra');
INSERT INTO Pessoa VALUES(10, 'Rui Samudio', '04-01-2001', '4490', 'Rua da Junqueira');
INSERT INTO Pessoa VALUES(11, 'Matilde Vale', '09-11-2000', '4480', 'Rua Nova');
INSERT INTO Pessoa VALUES(12, 'Ana Santos', '10-01-2000', '4480', 'Rua 1');
INSERT INTO Pessoa VALUES(13, 'Pedro Castro', '19-03-2000', '4860', 'Chacim');
INSERT INTO Pessoa VALUES(14, 'Bernardo Vaz', '25-08-2000', '4860', 'Rua de Outeirinho');
INSERT INTO Pessoa VALUES(15, 'Marta Vieitas', '12-01-1999', '3020', 'Avenida Sá da Bandeira');
INSERT INTO Pessoa VALUES(16, 'Ines Machado', '17-07-2000', '3020', 'Rua das Azeiteiras');
INSERT INTO Pessoa VALUES(17, 'Olena Shelvytska', '09-06-1998', '79007', 'Lviv Snow Stree');
INSERT INTO Pessoa VALUES(18, 'Beatriz Mendes', '01-06-2000', '4850', 'Centro da Maia');
INSERT INTO Pessoa VALUES(19, 'Marta Santos', '09-12-2001', '4425', 'Rua 1o de janeiro');
INSERT INTO Pessoa VALUES(20, 'Mafalda Silva', '25-06-1987', '4425', 'Rua 1o de maio');
INSERT INTO Pessoa VALUES(21, 'Diogo Figueiredo', '31-03-2000', '1900', 'Avenida Valente de Oliveira');
INSERT INTO Pessoa VALUES(22, 'Jose Arriscado', '22-2-2000', '1900', 'Avenida Afonso Costa');
INSERT INTO Pessoa VALUES(23, 'Inacio Vasconcelos', '11-06-1998', '1900', 'Avenida Afonso III');
INSERT INTO Pessoa VALUES(24, 'Diana Freitas', '24-07-1999', '4000', 'Avenida Cidade do Porto');
INSERT INTO Pessoa VALUES(25, 'Afonso Festas', '09-03-2006', '4000', 'Rua Escura');
INSERT INTO Pessoa VALUES(26, 'Alice Horta', '03-08-2000', '4000', 'Rua do Rosario');
INSERT INTO Pessoa VALUES(27, 'Carlos Lopes', '13-10-1999', '4000', 'Rua de Passos Manuel');
INSERT INTO Pessoa VALUES(28, 'Miguel Rodrigues', '01-02-2001', '4000', 'Rua de Sao Bento da Vitoria');
INSERT INTO Pessoa VALUES(29, 'Leonor Coelho', '17-03-2000', '4000', 'Rua de Miguel Bombarda');
INSERT INTO Pessoa VALUES(30, 'Telma Araujo', '12-09-2000', '4801', 'Rua de Santa Maria');
INSERT INTO Pessoa VALUES(31, 'Kurt Cobain', '20-02-1967', 98101, NULL);
INSERT INTO Pessoa VALUES(32, 'Krist Novoselic', '16-05-1965', 90220, NULL);
INSERT INTO Pessoa VALUES(33, 'Dave Grohl', '14-01-1969', 80892, NULL);
INSERT INTO Pessoa VALUES(34, 'Nate Mendel', '02-12-1968', 58235, NULL);
INSERT INTO Pessoa VALUES(35, 'Taylor Hawkins', '17-02-1972', 76008, NULL);
INSERT INTO Pessoa VALUES(36, 'Thomas Yorke', '07-10-1968', NULL, NULL);
INSERT INTO Pessoa VALUES(37, 'Johnny Greenwood', '05-11-1971', NULL, NULL);
INSERT INTO Pessoa VALUES(38, 'Colin Greenwood', '15-04-1968', NULL, NULL);
INSERT INTO Pessoa VALUES(39, 'Ed Obrien', '26-06-1969', NULL, NULL);
INSERT INTO Pessoa VALUES(40, 'Philip Selway', '23-05-1967', NULL, NULL);
INSERT INTO Pessoa VALUES(41, 'Billie Eilish', '18-12-2001', NULL, NULL);
INSERT INTO Pessoa VALUES(42, 'Hayley Williams', '27-12-1988', NULL, NULL);
INSERT INTO Pessoa VALUES(43, 'Taylor York', '17-12-1989', NULL, NULL);
INSERT INTO Pessoa VALUES(44, 'Zac Farro', '04-06-1990', NULL, NULL);
INSERT INTO Pessoa VALUES(45, 'Elizabeth Grant', '21-06-1985', NULL, NULL);
INSERT INTO Pessoa VALUES(46, 'Elena Tonra', '15-01-1990', NULL, NULL);
INSERT INTO Pessoa VALUES(47, 'Igor Haefeli', '07-03-1987', NULL, NULL);
INSERT INTO Pessoa VALUES(48, 'Remi Aguilella', '15-02-1977', NULL, NULL);
INSERT INTO Pessoa VALUES(49, 'Ella Yelich-OConnor', '07-11-1996', NULL, 'Epsom Auckland');
INSERT INTO Pessoa VALUES(50, 'Marshall Bruce Mathers', '17-10-1972', NULL, NULL);

-- Artista 
INSERT INTO Artista VALUES(31, 1987);
INSERT INTO Artista VALUES(32, 1987);
INSERT INTO Artista VALUES(33, 1987);
INSERT INTO Artista VALUES(34, 1994);
INSERT INTO Artista VALUES(35, 1994);
INSERT INTO Artista VALUES(36, '1985');
INSERT INTO Artista VALUES(37, '1985');
INSERT INTO Artista VALUES(38, '1985');
INSERT INTO Artista VALUES(39, '1985');
INSERT INTO Artista VALUES(40, '1985');
INSERT INTO Artista VALUES(41, '2015');
INSERT INTO Artista VALUES(42, '2003');
INSERT INTO Artista VALUES(43, '2001');
INSERT INTO Artista VALUES(44, '2004');
INSERT INTO Artista VALUES(45, '2005');
INSERT INTO Artista VALUES(46, '2010');
INSERT INTO Artista VALUES(47, '2010');
INSERT INTO Artista VALUES(48, '2010');
INSERT INTO Artista VALUES(49, '2009');
INSERT INTO Artista VALUES(50, '1988');

-- Utilizador 
INSERT INTO Utilizador VALUES(1, 'hugomguima@gmail.com', 'Huguima', 'gagdafgdfgfdsg');
INSERT INTO Utilizador VALUES(2, 'samue@hotmail.com', 'Samuh', 'asvvaevaf');
INSERT INTO Utilizador VALUES(3, 'pjbom.best@gmail.com', 'pjbom', 'asdfsad');
INSERT INTO Utilizador VALUES(4, 'pedro.nero@hotmail.com', 'pnero', 'asafs1');
INSERT INTO Utilizador VALUES(5, 'ana.monteiro@hotmail.com', 'amonteiro', 'njkfj');
INSERT INTO Utilizador VALUES(6, 'm.lopes798@gmail.com', 'MartaLopes798', 'm798');
INSERT INTO Utilizador VALUES(7, 'martafigueredo254@gmail.com', 'martafigueiredo00', 'design');
INSERT INTO Utilizador VALUES(8, 'rodrugsparties@gmail.com', 'Rfestas', 'jarreta');
INSERT INTO Utilizador VALUES(9, 'cmonteiro@gmail.com', 'CarlosMonteiro', 'mcmonteiro');
INSERT INTO Utilizador VALUES(10, 'laura_freitas@outlook.com', 'teste5', 'good_password');
INSERT INTO Utilizador VALUES(11, 'matildevale', 'Matile V.C.', 'catsAndDogs');
INSERT INTO Utilizador VALUES(12, 'Anasantos@gmail.com', 'Ana San', 'halelujah');
INSERT INTO Utilizador VALUES(13, 'PedroCastro@gmail.com', 'P. Castro', 'Amen');
INSERT INTO Utilizador VALUES(14, 'Bernasvaz468@gmail.com', 'Bern Vaz', 'passs');
INSERT INTO Utilizador VALUES(15, 'msvieitas@hotmail.com', 'm_Vieitas', 'protegido');
INSERT INTO Utilizador VALUES(16, 'inesmachado456@gmail.com', 'teste5', 'naoVaoDescobrir');
INSERT INTO Utilizador VALUES(17, 'Ole.Shelv@outlook.com', 'oShelvy', 'ukraine');
INSERT INTO Utilizador VALUES(18, 'ziniii@outlook.com', 'ZiniWhini', 'egirl1234');
INSERT INTO Utilizador VALUES(19, 'MartaSantos652@outlook.com', 'Marta Santos', 'santos123');
INSERT INTO Utilizador VALUES(20, 'Mfsilvaa01@outlook.com', 'Mafalda s01', 'lopes1243');
INSERT INTO Utilizador VALUES(21, 'digofigueiredo@gmail.com', 'digofixe', 'xxdigofixexx');
INSERT INTO Utilizador VALUES(22, 'zerisk@outlook.com', 'jose boy', 'zeboy2000');
INSERT INTO Utilizador VALUES(23, 'inacio_celos.com', 'Inacio Vasconcelos', 'inaskim');
INSERT INTO Utilizador VALUES(24, 'Dianamfreitas@gmail.com', 'Diana Freitas', 'adorolcom');
INSERT INTO Utilizador VALUES(25, 'memeboy254@outlook.com', 'Alphonso Parties', 'XxX420XxX');
INSERT INTO Utilizador VALUES(26, 'iamalice@outlook.com', 'Alice M. Horta', 'aMorta');
INSERT INTO Utilizador VALUES(27, 'c.lopes@gmail.com', 'teste5', '123456789');
INSERT INTO Utilizador VALUES(28, 'mike.rodriguez@gotmail.com', 'teste5', '123456789');
INSERT INTO Utilizador VALUES(29, 'bunnygirl@outlook.com', 'Leo C', '123456789');
INSERT INTO Utilizador VALUES(30, 'metallover@gmail.com', 'MC Araujo', '123456789');

-- Papel 
INSERT INTO Papel VALUES(1, 'Vocal');
INSERT INTO Papel VALUES(2, 'Guitarra');
INSERT INTO Papel VALUES(3, 'Piano');
INSERT INTO Papel VALUES(4, 'Bateria');
INSERT INTO Papel VALUES(5, 'Baixo');
INSERT INTO Papel VALUES(6, 'Viola');

-- EntidadeMusical 
INSERT INTO EntidadeMusical VALUES(1, 'Nirvana', 'imagem', 1987, 'Grande sucesso com o estilo grunge');
INSERT INTO EntidadeMusical VALUES(2, 'Foo Fighters', 'imagem', 1994, 'Criada após o fim dos Nirvana');
INSERT INTO EntidadeMusical VALUES(3, 'Radiohead', 'imagem', 1985, 'Creep foi o 1o e maior single deles');
INSERT INTO EntidadeMusical VALUES(4, 'Billie Eilish', 'imagem', 2016, 'Ficou famosa com apensa 17 anos!!');
INSERT INTO EntidadeMusical VALUES(5, 'Paramore', 'imagem', 2004, 'WE ARE PARAMORE!');
INSERT INTO EntidadeMusical VALUES(6, 'Lana Del Rey', 'imagem', 2005, 'Utiliza frequentemente referencias ao pop americano');
INSERT INTO EntidadeMusical VALUES(7, 'Daughter', 'imagem', 2009, 'Foi responsavel pela banda sonora de Life is Strange');
INSERT INTO EntidadeMusical VALUES(8, 'Lorde', 'imagem', 1988, ' nomeada Mulher Do Ano pela MTV, em 2013');
INSERT INTO EntidadeMusical VALUES(9, 'Eminem', 'imagem', 1988, 'Melhor rapper de sempre');

-- Album 
INSERT INTO Album VALUES(1, 'Nevermind', 'capa', 'YEAR');
INSERT INTO Album VALUES(2, 'In Utero', 'capa', 'YEAR');
INSERT INTO Album VALUES(3, 'Concrete and Gold - ', 'capa', 'YEAR');
INSERT INTO Album VALUES(4, 'OK Computer', 'https://i.imgur.com/7Prc1JI.jpg', '1997');
INSERT INTO Album VALUES(5, 'When We All Fall Asleep, Where Do We Go?', 'https://i.imgur.com/181OJ2a.png', '2019');
INSERT INTO Album VALUES(6, 'Brand New Eyes', 'https://i.imgur.com/2zUv7QL.jpg', '2009');
INSERT INTO Album VALUES(7, 'All We Know Is Falling', 'https://i.imgur.com/Gh2Y21E.jpg', '2005');
INSERT INTO Album VALUES(8, 'Born to Die', 'capa', 'YEAR');
INSERT INTO Album VALUES(9, 'If You Leav', 'capa', '2013');
INSERT INTO Album VALUES(10, 'Melodrama', 'capa', 'YEAR');
INSERT INTO Album VALUES(11, 'The Eminem Show', 'capa', 'YEAR');

-- Musica 
INSERT INTO Musica VALUES(1, 1, 'Smells Like Teen Spirit', 'DURACAO');
INSERT INTO Musica VALUES(2, 1, 'In Bloom', 'DURACAO');
INSERT INTO Musica VALUES(3, 1, 'Come As You Are', 'DURACAO');
INSERT INTO Musica VALUES(4, 1, 'Breed', 'DURACAO');
INSERT INTO Musica VALUES(5, 1, 'Lithium', 'DURACAO');
INSERT INTO Musica VALUES(6, 1, 'Polly', 'DURACAO');
INSERT INTO Musica VALUES(7, 1, 'Territorial Pissings', 'DURACAO');
INSERT INTO Musica VALUES(8, 1, 'Drain You', 'DURACAO');
INSERT INTO Musica VALUES(9, 1, 'Lounge Act', 'DURACAO');
INSERT INTO Musica VALUES(10, 1, 'Stay Away', 'DURACAO');
INSERT INTO Musica VALUES(11, 1, 'On A Plain', 'DURACAO');
INSERT INTO Musica VALUES(12, 1, 'Something In The Way', 'DURACAO');
INSERT INTO Musica VALUES(13, 2, 'Serve The Servants', 'DURACAO');
INSERT INTO Musica VALUES(14, 2, 'Scentless Apprentice', 'DURACAO');
INSERT INTO Musica VALUES(15, 2, 'Heart-shaped Box', 'DURACAO');
INSERT INTO Musica VALUES(16, 2, 'Rape Me', 'DURACAO');
INSERT INTO Musica VALUES(17, 2, 'Frances Farmer Will Have Her Revenge On Seattle', 'DURACAO');
INSERT INTO Musica VALUES(18, 2, 'Dumb', 'DURACAO');
INSERT INTO Musica VALUES(19, 2, 'Very Ape', 'DURACAO');
INSERT INTO Musica VALUES(20, 2, 'Milk It', 'DURACAO');
INSERT INTO Musica VALUES(21, 2, 'Pennyroyal Tea', 'DURACAO');
INSERT INTO Musica VALUES(22, 2, 'Radio Friendly Unit Shifter', 'DURACAO');
INSERT INTO Musica VALUES(23, 2, 'Tourette`s', 'DURACAO');
INSERT INTO Musica VALUES(24, 2, 'All Apologies', 'DURACAO');
INSERT INTO Musica VALUES(25, 2, 'Gallons Of Rubbing Alcohol Flow Through The Strip', 'DURACAO');
INSERT INTO Musica VALUES(26, 3, 'T-Shirt', 'DURACAO');
INSERT INTO Musica VALUES(27, 3, 'Run', 'DURACAO');
INSERT INTO Musica VALUES(28, 3, 'Make It Right', 'DURACAO');
INSERT INTO Musica VALUES(29, 3, 'The Sky Is a Neighborhood', 'DURACAO');
INSERT INTO Musica VALUES(30, 3, 'Concrete and Gold', 'DURACAO');
INSERT INTO Musica VALUES(31, 4, 'Karma Police', 'DURACAO');
INSERT INTO Musica VALUES(32, 4, 'Fitter, Happier', 'DURACAO');
INSERT INTO Musica VALUES(33, 4, 'Electioneering', 'DURACAO');
INSERT INTO Musica VALUES(34, 4, 'Climbing Up The Walls', 'DURACAO');
INSERT INTO Musica VALUES(35, 4, 'No Surprises', 'DURACAO');
INSERT INTO Musica VALUES(36, 4, 'Lucky', 'DURACAO');
INSERT INTO Musica VALUES(37, 4, 'The Tourist', 'DURACAO');
INSERT INTO Musica VALUES(38, 5, 'Bad Guy', 'DURACAO');
INSERT INTO Musica VALUES(39, 5, 'Xanny', 'DURACAO');
INSERT INTO Musica VALUES(40, 5, 'You Should See Me In a Crown', 'DURACAO');
INSERT INTO Musica VALUES(41, 5, 'All The Good Girls Go To Hell', 'DURACAO');
INSERT INTO Musica VALUES(42, 5, 'My Strange Addiction', 'DURACAO');
INSERT INTO Musica VALUES(43, 5, 'Bury a Friend', 'DURACAO');
INSERT INTO Musica VALUES(44, 5, 'Ilomilo', 'DURACAO');
INSERT INTO Musica VALUES(45, 5, 'Listen Before I Go', 'DURACAO');
INSERT INTO Musica VALUES(46, 5, 'I Love You', 'DURACAO');
INSERT INTO Musica VALUES(47, 5, 'Goodbye', 'DURACAO');
INSERT INTO Musica VALUES(48, 6, 'Careful', 'DURACAO');
INSERT INTO Musica VALUES(49, 6, 'Ignorance', 'DURACAO');
INSERT INTO Musica VALUES(50, 6, 'Playing God', 'DURACAO');
INSERT INTO Musica VALUES(51, 6, 'Brick By Boring Brick', 'DURACAO');
INSERT INTO Musica VALUES(52, 6, 'Turn It Off', 'DURACAO');
INSERT INTO Musica VALUES(53, 6, 'The Only Exception', 'DURACAO');
INSERT INTO Musica VALUES(54, 6, 'Feeling Sorry', 'DURACAO');
INSERT INTO Musica VALUES(55, 6, 'Looking Up', 'DURACAO');
INSERT INTO Musica VALUES(56, 6, 'Where The Lines Overlap', 'DURACAO');
INSERT INTO Musica VALUES(57, 6, 'Misguided Ghosts', 'DURACAO');
INSERT INTO Musica VALUES(58, 6, 'All I Wanted', 'DURACAO');
INSERT INTO Musica VALUES(59, 7, 'All We Know', 'DURACAO');
INSERT INTO Musica VALUES(60, 7, 'Pressure', 'DURACAO');
INSERT INTO Musica VALUES(61, 7, 'Emergency', 'DURACAO');
INSERT INTO Musica VALUES(62, 7, 'Brighter', 'DURACAO');
INSERT INTO Musica VALUES(63, 7, 'Here We Go Again', 'DURACAO');
INSERT INTO Musica VALUES(64, 7, 'Never Let This Go', 'DURACAO');
INSERT INTO Musica VALUES(65, 7, 'Whoa', 'DURACAO');
INSERT INTO Musica VALUES(66, 7, 'Conspiracy', 'DURACAO');
INSERT INTO Musica VALUES(67, 7, 'Franklin', 'DURACAO');
INSERT INTO Musica VALUES(68, 7, 'My Heart', 'DURACAO');
INSERT INTO Musica VALUES(69, 8, 'Born To Die', 'DURACAO');
INSERT INTO Musica VALUES(70, 8, 'Off To The Races', 'DURACAO');
INSERT INTO Musica VALUES(71, 8, 'Blue Jeans', 'DURACAO');
INSERT INTO Musica VALUES(72, 8, 'Video Games', 'DURACAO');
INSERT INTO Musica VALUES(73, 8, 'Diet Mountain Dew', 'DURACAO');
INSERT INTO Musica VALUES(74, 8, 'National Anthem', 'DURACAO');
INSERT INTO Musica VALUES(75, 8, 'Dark Paradise', 'DURACAO');
INSERT INTO Musica VALUES(76, 8, 'Radio', 'DURACAO');
INSERT INTO Musica VALUES(77, 8, 'Carmen', 'DURACAO');
INSERT INTO Musica VALUES(78, 8, 'Million Dollar Man', 'DURACAO');
INSERT INTO Musica VALUES(79, 8, 'Summertime Sadness', 'DURACAO');
INSERT INTO Musica VALUES(80, 8, 'This Is What Makes Us Girls', 'DURACAO');
INSERT INTO Musica VALUES(81, 8, 'Without You', 'DURACAO');
INSERT INTO Musica VALUES(82, 8, 'Lolita', 'DURACAO');
INSERT INTO Musica VALUES(83, 8, 'Lucky Ones', 'DURACAO');
INSERT INTO Musica VALUES(84, 9, 'Winter', 'DURACAO');
INSERT INTO Musica VALUES(85, 9, 'Smother', 'DURACAO');
INSERT INTO Musica VALUES(86, 9, 'Youth', 'DURACAO');
INSERT INTO Musica VALUES(87, 9, 'Still', 'DURACAO');
INSERT INTO Musica VALUES(88, 9, 'Lifeforms', 'DURACAO');
INSERT INTO Musica VALUES(89, 9, 'Tomorrow', 'DURACAO');
INSERT INTO Musica VALUES(90, 9, 'Human', 'DURACAO');
INSERT INTO Musica VALUES(91, 9, 'Touch', 'DURACAO');
INSERT INTO Musica VALUES(92, 9, 'Amsterdam', 'DURACAO');
INSERT INTO Musica VALUES(93, 9, 'Shallows', 'DURACAO');
INSERT INTO Musica VALUES(94, 10, 'Green Light', 'DURACAO');
INSERT INTO Musica VALUES(95, 10, 'Sober', 'DURACAO');
INSERT INTO Musica VALUES(96, 10, 'Homemade Dynamite', 'DURACAO');
INSERT INTO Musica VALUES(97, 10, 'The Louvre', 'DURACAO');
INSERT INTO Musica VALUES(98, 10, 'Liability', 'DURACAO');
INSERT INTO Musica VALUES(99, 10, 'Hard Feelings / Loveless', 'DURACAO');
INSERT INTO Musica VALUES(100, 10, 'Sober Ii (Melodrama)', 'DURACAO');
INSERT INTO Musica VALUES(101, 10, 'Writer In The Dark', 'DURACAO');
INSERT INTO Musica VALUES(102, 10, 'Supercut', 'DURACAO');
INSERT INTO Musica VALUES(103, 10, 'Liability (Reprise)', 'DURACAO');
INSERT INTO Musica VALUES(104, 10, 'Perfect Places', 'DURACAO');
INSERT INTO Musica VALUES(105, 11, 'Curtains Up ( Skit)', 'DURACAO');
INSERT INTO Musica VALUES(106, 11, 'White America', 'DURACAO');
INSERT INTO Musica VALUES(107, 11, 'Business', 'DURACAO');
INSERT INTO Musica VALUES(108, 11, 'Cleanin Out My Closet', 'DURACAO');
INSERT INTO Musica VALUES(109, 11, 'Square Dance', 'DURACAO');
INSERT INTO Musica VALUES(110, 11, 'The Kiss', 'DURACAO');
INSERT INTO Musica VALUES(111, 11, 'Soldier', 'DURACAO');
INSERT INTO Musica VALUES(112, 11, 'Say Goodbye Hollywood', 'DURACAO');
INSERT INTO Musica VALUES(113, 11, 'Drips', 'DURACAO');
INSERT INTO Musica VALUES(114, 11, 'Without Me', 'DURACAO');
INSERT INTO Musica VALUES(115, 11, 'Paul Rosenberg', 'DURACAO');
INSERT INTO Musica VALUES(116, 11, 'Sing For The Moment', 'DURACAO');
INSERT INTO Musica VALUES(117, 11, 'Superman', 'DURACAO');
INSERT INTO Musica VALUES(118, 11, 'Hailies Song', 'DURACAO');
INSERT INTO Musica VALUES(119, 11, 'Steve Berman', 'DURACAO');
INSERT INTO Musica VALUES(120, 11, 'When The Music Stops', 'DURACAO');
INSERT INTO Musica VALUES(121, 11, 'Say What You Say', 'DURACAO');
INSERT INTO Musica VALUES(122, 11, 'Till I Collapse', 'DURACAO');
INSERT INTO Musica VALUES(123, 11, 'My Dads Gone Crazy', 'DURACAO');
INSERT INTO Musica VALUES(124, 11, 'Curtains Close', 'DURACAO');

-- EstiloMusical 
INSERT INTO EstiloMusical VALUES(1, 'Rock');
INSERT INTO EstiloMusical VALUES(2, 'Indie');
INSERT INTO EstiloMusical VALUES(3, 'Pop');
INSERT INTO EstiloMusical VALUES(4, 'Grunge');
INSERT INTO EstiloMusical VALUES(5, 'Hip Hop');

-- Playlist 
INSERT INTO Playlist VALUES(1, 1, 'I Love 90', 'imagem', '2020', 'Best songs of 90s', 0);
INSERT INTO Playlist VALUES(2, 2, 'Indie', 'imagem', '2020', 'New Indie Trend', 0);
INSERT INTO Playlist VALUES(3, 3, 'Me and my Friends', 'imagem', '2020', 'Put your favorite songs here!', 1);

-- Sessao 
INSERT INTO Sessao VALUES(1, '16-03-2020');
INSERT INTO Sessao VALUES(2, '16-03-2020');
INSERT INTO Sessao VALUES(3, '16-03-2020');
INSERT INTO Sessao VALUES(4, '17-03-2020');
INSERT INTO Sessao VALUES(5, '17-03-2020');
INSERT INTO Sessao VALUES(6, '18-03-2020');
INSERT INTO Sessao VALUES(7, '18-03-2020');
INSERT INTO Sessao VALUES(8, '19-03-2020');
INSERT INTO Sessao VALUES(9, '21-03-2020');
INSERT INTO Sessao VALUES(10, '22-03-2020');
INSERT INTO Sessao VALUES(11, '22-03-2020');
INSERT INTO Sessao VALUES(12, '23-03-2020');
INSERT INTO Sessao VALUES(13, '25-03-2020');
INSERT INTO Sessao VALUES(14, '25-03-2020');
INSERT INTO Sessao VALUES(15, '26-03-2020');
INSERT INTO Sessao VALUES(16, '28-03-2020');
INSERT INTO Sessao VALUES(17, '30-03-2020');
INSERT INTO Sessao VALUES(18, '31-03-2020');
INSERT INTO Sessao VALUES(19, '31-03-2020');
INSERT INTO Sessao VALUES(20, '31-03-2020');
INSERT INTO Sessao VALUES(21, '01-04-2020');
INSERT INTO Sessao VALUES(22, '01-04-2020');
INSERT INTO Sessao VALUES(23, '01-04-2020');
INSERT INTO Sessao VALUES(24, '02-04-2020');
INSERT INTO Sessao VALUES(25, '02-04-2020');
INSERT INTO Sessao VALUES(26, '03-04-2020');
INSERT INTO Sessao VALUES(27, '03-04-2020');
INSERT INTO Sessao VALUES(28, '04-04-2020');
INSERT INTO Sessao VALUES(29, '04-04-2020');
INSERT INTO Sessao VALUES(30, '04-04-2020');

-- TempoOuvido 
INSERT INTO TempoOuvido VALUES(1, 1, '270');
INSERT INTO TempoOuvido VALUES(1, 2, '340');
INSERT INTO TempoOuvido VALUES(2, 3, '420');
INSERT INTO TempoOuvido VALUES(2, 20, '80');
INSERT INTO TempoOuvido VALUES(2, 21, '120');
INSERT INTO TempoOuvido VALUES(2, 22, '210');
INSERT INTO TempoOuvido VALUES(2, 23, '267');
INSERT INTO TempoOuvido VALUES(2, 24, '546');
INSERT INTO TempoOuvido VALUES(2, 25, '126');
INSERT INTO TempoOuvido VALUES(2, 26, '150');
INSERT INTO TempoOuvido VALUES(2, 27, '220');
INSERT INTO TempoOuvido VALUES(2, 28, '462');
INSERT INTO TempoOuvido VALUES(2, 29, '236');
INSERT INTO TempoOuvido VALUES(2, 30, '90');
INSERT INTO TempoOuvido VALUES(2, 31, '99');
INSERT INTO TempoOuvido VALUES(2, 32, '136');
INSERT INTO TempoOuvido VALUES(2, 33, '160');
INSERT INTO TempoOuvido VALUES(2, 34, '200');
INSERT INTO TempoOuvido VALUES(2, 35, '110');
INSERT INTO TempoOuvido VALUES(2, 36, '145');
INSERT INTO TempoOuvido VALUES(2, 37, '139');
INSERT INTO TempoOuvido VALUES(3, 1, '154');
INSERT INTO TempoOuvido VALUES(3, 2, '123');
INSERT INTO TempoOuvido VALUES(3, 3, '321');
INSERT INTO TempoOuvido VALUES(3, 4, '152');
INSERT INTO TempoOuvido VALUES(3, 5, '136');
INSERT INTO TempoOuvido VALUES(3, 6, '178');
INSERT INTO TempoOuvido VALUES(3, 7, '189');
INSERT INTO TempoOuvido VALUES(3, 8, '154');
INSERT INTO TempoOuvido VALUES(3, 9, '199');
INSERT INTO TempoOuvido VALUES(3, 10, '231');
INSERT INTO TempoOuvido VALUES(3, 11, '426');
INSERT INTO TempoOuvido VALUES(4, 13, '126');
INSERT INTO TempoOuvido VALUES(4, 14, '120');
INSERT INTO TempoOuvido VALUES(4, 15, '150');
INSERT INTO TempoOuvido VALUES(4, 16, '126');
INSERT INTO TempoOuvido VALUES(4, 17, '230');
INSERT INTO TempoOuvido VALUES(4, 18, '121');
INSERT INTO TempoOuvido VALUES(4, 19, '323');
INSERT INTO TempoOuvido VALUES(4, 20, '204');
INSERT INTO TempoOuvido VALUES(5, 13, '180');
INSERT INTO TempoOuvido VALUES(5, 15, '210');
INSERT INTO TempoOuvido VALUES(5, 34, '100');
INSERT INTO TempoOuvido VALUES(6, 33, '120');
INSERT INTO TempoOuvido VALUES(6, 35, '125');
INSERT INTO TempoOuvido VALUES(6, 19, '186');
INSERT INTO TempoOuvido VALUES(6, 13, '183');
INSERT INTO TempoOuvido VALUES(7, 33, '164');
INSERT INTO TempoOuvido VALUES(7, 34, '176');

-- Desempenha 
INSERT INTO Desempenha VALUES(31, 1);
INSERT INTO Desempenha VALUES(31, 2);
INSERT INTO Desempenha VALUES(32, 5);
INSERT INTO Desempenha VALUES(33, 1);
INSERT INTO Desempenha VALUES(33, 4);
INSERT INTO Desempenha VALUES(34, 5);
INSERT INTO Desempenha VALUES(35, 4);
INSERT INTO Desempenha VALUES(36, 1);
INSERT INTO Desempenha VALUES(37, 1);
INSERT INTO Desempenha VALUES(38, 1);
INSERT INTO Desempenha VALUES(39, 2);
INSERT INTO Desempenha VALUES(40, 2);
INSERT INTO Desempenha VALUES(41, 1);
INSERT INTO Desempenha VALUES(41, 2);
INSERT INTO Desempenha VALUES(42, 1);
INSERT INTO Desempenha VALUES(42, 3);
INSERT INTO Desempenha VALUES(43, 2);
INSERT INTO Desempenha VALUES(44, 4);
INSERT INTO Desempenha VALUES(45, 1);
INSERT INTO Desempenha VALUES(45, 6);
INSERT INTO Desempenha VALUES(46, 1);
INSERT INTO Desempenha VALUES(47, 2);
INSERT INTO Desempenha VALUES(48, 4);
INSERT INTO Desempenha VALUES(49, 1);
INSERT INTO Desempenha VALUES(49, 6);
INSERT INTO Desempenha VALUES(50, 1);

-- Possui 
INSERT INTO Possui VALUES(1, 1);
INSERT INTO Possui VALUES(1, 2);
INSERT INTO Possui VALUES(1, 4);
INSERT INTO Possui VALUES(1, 5);
INSERT INTO Possui VALUES(2, 1);
INSERT INTO Possui VALUES(2, 4);
INSERT INTO Possui VALUES(2, 5);
INSERT INTO Possui VALUES(3, 1);
INSERT INTO Possui VALUES(3, 2);
INSERT INTO Possui VALUES(4, 1);
INSERT INTO Possui VALUES(5, 1);
INSERT INTO Possui VALUES(5, 2);
INSERT INTO Possui VALUES(5, 3);
INSERT INTO Possui VALUES(5, 4);
INSERT INTO Possui VALUES(6, 1);
INSERT INTO Possui VALUES(6, 6);
INSERT INTO Possui VALUES(7, 1);
INSERT INTO Possui VALUES(7, 2);
INSERT INTO Possui VALUES(7, 4);
INSERT INTO Possui VALUES(8, 1);
INSERT INTO Possui VALUES(8, 6);
INSERT INTO Possui VALUES(9, 1);

-- Membro 
INSERT INTO Membro VALUES(31, 1);
INSERT INTO Membro VALUES(32, 1);
INSERT INTO Membro VALUES(33, 1);
INSERT INTO Membro VALUES(34, 2);
INSERT INTO Membro VALUES(35, 2);
INSERT INTO Membro VALUES(36, 3);
INSERT INTO Membro VALUES(37, 3);
INSERT INTO Membro VALUES(38, 3);
INSERT INTO Membro VALUES(39, 3);
INSERT INTO Membro VALUES(40, 3);
INSERT INTO Membro VALUES(41, 4);
INSERT INTO Membro VALUES(42, 5);
INSERT INTO Membro VALUES(43, 5);
INSERT INTO Membro VALUES(44, 5);
INSERT INTO Membro VALUES(45, 6);
INSERT INTO Membro VALUES(46, 7);
INSERT INTO Membro VALUES(47, 7);
INSERT INTO Membro VALUES(48, 7);
INSERT INTO Membro VALUES(49, 8);
INSERT INTO Membro VALUES(50, 9);

-- Compoe 
INSERT INTO Compoe VALUES(1, 1);
INSERT INTO Compoe VALUES(1, 2);
INSERT INTO Compoe VALUES(2, 3);
INSERT INTO Compoe VALUES(3, 4);
INSERT INTO Compoe VALUES(4, 5);
INSERT INTO Compoe VALUES(5, 6);
INSERT INTO Compoe VALUES(5, 7);
INSERT INTO Compoe VALUES(6, 8);
INSERT INTO Compoe VALUES(7, 9);
INSERT INTO Compoe VALUES(8, 10);
INSERT INTO Compoe VALUES(9, 11);

-- FavoritoAlbum 
INSERT INTO FavoritoAlbum VALUES(1, 1);
INSERT INTO FavoritoAlbum VALUES(2, 2);
INSERT INTO FavoritoAlbum VALUES(2, 3);
INSERT INTO FavoritoAlbum VALUES(2, 4);
INSERT INTO FavoritoAlbum VALUES(3, 1);
INSERT INTO FavoritoAlbum VALUES(4, 1);
INSERT INTO FavoritoAlbum VALUES(5, 3);
INSERT INTO FavoritoAlbum VALUES(6, 1);
INSERT INTO FavoritoAlbum VALUES(7, 2);
INSERT INTO FavoritoAlbum VALUES(8, 3);
INSERT INTO FavoritoAlbum VALUES(9, 4);
INSERT INTO FavoritoAlbum VALUES(10, 5);
INSERT INTO FavoritoAlbum VALUES(10, 6);
INSERT INTO FavoritoAlbum VALUES(11, 6);
INSERT INTO FavoritoAlbum VALUES(12, 6);
INSERT INTO FavoritoAlbum VALUES(12, 7);
INSERT INTO FavoritoAlbum VALUES(12, 8);
INSERT INTO FavoritoAlbum VALUES(13, 2);
INSERT INTO FavoritoAlbum VALUES(14, 3);
INSERT INTO FavoritoAlbum VALUES(15, 7);
INSERT INTO FavoritoAlbum VALUES(16, 8);
INSERT INTO FavoritoAlbum VALUES(17, 9);
INSERT INTO FavoritoAlbum VALUES(18, 11);
INSERT INTO FavoritoAlbum VALUES(19, 8);
INSERT INTO FavoritoAlbum VALUES(20, 9);
INSERT INTO FavoritoAlbum VALUES(21, 11);
INSERT INTO FavoritoAlbum VALUES(22, 10);
INSERT INTO FavoritoAlbum VALUES(23, 10);
INSERT INTO FavoritoAlbum VALUES(23, 1);
INSERT INTO FavoritoAlbum VALUES(24, 2);
INSERT INTO FavoritoAlbum VALUES(24, 3);
INSERT INTO FavoritoAlbum VALUES(25, 4);
INSERT INTO FavoritoAlbum VALUES(26, 2);
INSERT INTO FavoritoAlbum VALUES(27, 6);
INSERT INTO FavoritoAlbum VALUES(27, 7);
INSERT INTO FavoritoAlbum VALUES(27, 9);
INSERT INTO FavoritoAlbum VALUES(28, 11);
INSERT INTO FavoritoAlbum VALUES(29, 10);
INSERT INTO FavoritoAlbum VALUES(29, 3);
INSERT INTO FavoritoAlbum VALUES(30, 1);
INSERT INTO FavoritoAlbum VALUES(30, 4);
INSERT INTO FavoritoAlbum VALUES(30, 11);

-- FavoritoMusica 
INSERT INTO FavoritoMusica VALUES(2, 10, '15-03-2020');
INSERT INTO FavoritoMusica VALUES(1, 33, '02-04-2020');
INSERT INTO FavoritoMusica VALUES(1, 34, '02-04-2020');
INSERT INTO FavoritoMusica VALUES(1, 35, '23-03-2020');
INSERT INTO FavoritoMusica VALUES(3, 6, '23-03-2020');
INSERT INTO FavoritoMusica VALUES(3, 7, '25-03-2020');
INSERT INTO FavoritoMusica VALUES(3, 8, '25-03-2020');
INSERT INTO FavoritoMusica VALUES(4, 5, '26-03-2020');
INSERT INTO FavoritoMusica VALUES(4, 6, '28-03-2020');
INSERT INTO FavoritoMusica VALUES(5, 7, '28-03-2020');
INSERT INTO FavoritoMusica VALUES(6, 8, '29-03-2020');
INSERT INTO FavoritoMusica VALUES(6, 12, '29-03-2020');
INSERT INTO FavoritoMusica VALUES(6, 34, '29-03-2020');
INSERT INTO FavoritoMusica VALUES(7, 5, '31-03-2020');
INSERT INTO FavoritoMusica VALUES(8, 33, '01-04-2020');
INSERT INTO FavoritoMusica VALUES(8, 24, '01-04-2020');
INSERT INTO FavoritoMusica VALUES(9, 5, '01-04-2020');
INSERT INTO FavoritoMusica VALUES(11, 10, '02-04-2020');
INSERT INTO FavoritoMusica VALUES(11, 33, '02-04-2020');
INSERT INTO FavoritoMusica VALUES(12, 34, '02-04-2020');
INSERT INTO FavoritoMusica VALUES(13, 35, '22-04-2020');
INSERT INTO FavoritoMusica VALUES(13, 6, '02-04-2020');
INSERT INTO FavoritoMusica VALUES(14, 7, '02-04-2020');
INSERT INTO FavoritoMusica VALUES(15, 7, '02-04-2020');
INSERT INTO FavoritoMusica VALUES(15, 5, '02-04-2020');
INSERT INTO FavoritoMusica VALUES(16, 6, '02-04-2020');
INSERT INTO FavoritoMusica VALUES(17, 7, '02-04-2020');
INSERT INTO FavoritoMusica VALUES(17, 8, '02-04-2020');
INSERT INTO FavoritoMusica VALUES(18, 5, '03-04-2020');
INSERT INTO FavoritoMusica VALUES(18, 36, '03-04-2020');
INSERT INTO FavoritoMusica VALUES(19, 5, '03-04-2020');
INSERT INTO FavoritoMusica VALUES(20, 27, '03-04-2020');
INSERT INTO FavoritoMusica VALUES(21, 22, '03-04-2020');
INSERT INTO FavoritoMusica VALUES(22, 12, '03-04-2020');
INSERT INTO FavoritoMusica VALUES(22, 15, '03-04-2020');
INSERT INTO FavoritoMusica VALUES(23, 31, '03-04-2020');
INSERT INTO FavoritoMusica VALUES(24, 33, '03-04-2020');
INSERT INTO FavoritoMusica VALUES(25, 32, '04-04-2020');
INSERT INTO FavoritoMusica VALUES(26, 1, '04-04-2020');
INSERT INTO FavoritoMusica VALUES(26, 6, '04-04-2020');
INSERT INTO FavoritoMusica VALUES(27, 3, '04-04-2020');
INSERT INTO FavoritoMusica VALUES(27, 5, '04-04-2020');
INSERT INTO FavoritoMusica VALUES(28, 21, '04-04-2020');
INSERT INTO FavoritoMusica VALUES(28, 27, '04-04-2020');
INSERT INTO FavoritoMusica VALUES(28, 14, '04-04-2020');
INSERT INTO FavoritoMusica VALUES(29, 14, '04-04-2020');
INSERT INTO FavoritoMusica VALUES(30, 15, '04-04-2020');
INSERT INTO FavoritoMusica VALUES(30, 5, '04-04-2020');
INSERT INTO FavoritoMusica VALUES(30, 33, '04-04-2020');
INSERT INTO FavoritoMusica VALUES(30, 34, '04-04-2020');
INSERT INTO FavoritoMusica VALUES(30, 35, '04-04-2020');

-- FavoritoPlaylist 
INSERT INTO FavoritoPlaylist VALUES(3, 1);
INSERT INTO FavoritoPlaylist VALUES(2, 3);
INSERT INTO FavoritoPlaylist VALUES(1, 2);
INSERT INTO FavoritoPlaylist VALUES(4, 1);
INSERT INTO FavoritoPlaylist VALUES(4, 3);
INSERT INTO FavoritoPlaylist VALUES(5, 3);
INSERT INTO FavoritoPlaylist VALUES(6, 2);
INSERT INTO FavoritoPlaylist VALUES(7, 1);
INSERT INTO FavoritoPlaylist VALUES(7, 2);
INSERT INTO FavoritoPlaylist VALUES(8, 3);
INSERT INTO FavoritoPlaylist VALUES(9, 1);
INSERT INTO FavoritoPlaylist VALUES(10, 1);
INSERT INTO FavoritoPlaylist VALUES(10, 2);
INSERT INTO FavoritoPlaylist VALUES(11, 2);
INSERT INTO FavoritoPlaylist VALUES(12, 1);
INSERT INTO FavoritoPlaylist VALUES(12, 3);
INSERT INTO FavoritoPlaylist VALUES(13, 3);
INSERT INTO FavoritoPlaylist VALUES(14, 2);
INSERT INTO FavoritoPlaylist VALUES(15, 1);
INSERT INTO FavoritoPlaylist VALUES(16, 3);
INSERT INTO FavoritoPlaylist VALUES(17, 2);
INSERT INTO FavoritoPlaylist VALUES(18, 1);
INSERT INTO FavoritoPlaylist VALUES(18, 2);
INSERT INTO FavoritoPlaylist VALUES(19, 3);
INSERT INTO FavoritoPlaylist VALUES(20, 1);
INSERT INTO FavoritoPlaylist VALUES(22, 1);
INSERT INTO FavoritoPlaylist VALUES(23, 2);
INSERT INTO FavoritoPlaylist VALUES(24, 2);
INSERT INTO FavoritoPlaylist VALUES(25, 2);
INSERT INTO FavoritoPlaylist VALUES(26, 3);
INSERT INTO FavoritoPlaylist VALUES(27, 1);
INSERT INTO FavoritoPlaylist VALUES(28, 1);
INSERT INTO FavoritoPlaylist VALUES(30, 1);
INSERT INTO FavoritoPlaylist VALUES(30, 2);
INSERT INTO FavoritoPlaylist VALUES(30, 3);

-- Colabora 
INSERT INTO Colabora VALUES(1, 3);
INSERT INTO Colabora VALUES(3, 3);

-- EstiloMusica 
INSERT INTO EstiloMusica VALUES(1, 1);
INSERT INTO EstiloMusica VALUES(1, 2);
INSERT INTO EstiloMusica VALUES(1, 3);
INSERT INTO EstiloMusica VALUES(1, 4);
INSERT INTO EstiloMusica VALUES(1, 5);
INSERT INTO EstiloMusica VALUES(1, 6);
INSERT INTO EstiloMusica VALUES(1, 7);
INSERT INTO EstiloMusica VALUES(1, 8);
INSERT INTO EstiloMusica VALUES(1, 9);
INSERT INTO EstiloMusica VALUES(1, 10);
INSERT INTO EstiloMusica VALUES(1, 11);
INSERT INTO EstiloMusica VALUES(1, 12);
INSERT INTO EstiloMusica VALUES(1, 13);
INSERT INTO EstiloMusica VALUES(1, 14);
INSERT INTO EstiloMusica VALUES(1, 15);
INSERT INTO EstiloMusica VALUES(1, 16);
INSERT INTO EstiloMusica VALUES(1, 17);
INSERT INTO EstiloMusica VALUES(1, 18);
INSERT INTO EstiloMusica VALUES(1, 19);
INSERT INTO EstiloMusica VALUES(1, 20);
INSERT INTO EstiloMusica VALUES(1, 21);
INSERT INTO EstiloMusica VALUES(1, 22);
INSERT INTO EstiloMusica VALUES(1, 23);
INSERT INTO EstiloMusica VALUES(1, 24);
INSERT INTO EstiloMusica VALUES(1, 25);
INSERT INTO EstiloMusica VALUES(2, 1);
INSERT INTO EstiloMusica VALUES(2, 2);
INSERT INTO EstiloMusica VALUES(2, 3);
INSERT INTO EstiloMusica VALUES(2, 4);
INSERT INTO EstiloMusica VALUES(2, 5);
INSERT INTO EstiloMusica VALUES(2, 6);
INSERT INTO EstiloMusica VALUES(2, 7);
INSERT INTO EstiloMusica VALUES(2, 8);
INSERT INTO EstiloMusica VALUES(2, 9);
INSERT INTO EstiloMusica VALUES(2, 10);
INSERT INTO EstiloMusica VALUES(2, 11);
INSERT INTO EstiloMusica VALUES(2, 12);
INSERT INTO EstiloMusica VALUES(2, 13);
INSERT INTO EstiloMusica VALUES(2, 14);
INSERT INTO EstiloMusica VALUES(2, 15);
INSERT INTO EstiloMusica VALUES(2, 16);
INSERT INTO EstiloMusica VALUES(2, 17);
INSERT INTO EstiloMusica VALUES(2, 18);
INSERT INTO EstiloMusica VALUES(2, 19);
INSERT INTO EstiloMusica VALUES(2, 20);
INSERT INTO EstiloMusica VALUES(2, 21);
INSERT INTO EstiloMusica VALUES(2, 22);
INSERT INTO EstiloMusica VALUES(2, 23);
INSERT INTO EstiloMusica VALUES(2, 24);
INSERT INTO EstiloMusica VALUES(2, 25);
INSERT INTO EstiloMusica VALUES(1, 26);
INSERT INTO EstiloMusica VALUES(1, 27);
INSERT INTO EstiloMusica VALUES(1, 28);
INSERT INTO EstiloMusica VALUES(1, 29);
INSERT INTO EstiloMusica VALUES(2, 29);
INSERT INTO EstiloMusica VALUES(1, 30);
INSERT INTO EstiloMusica VALUES(1, 31);
INSERT INTO EstiloMusica VALUES(1, 32);
INSERT INTO EstiloMusica VALUES(1, 33);
INSERT INTO EstiloMusica VALUES(1, 34);
INSERT INTO EstiloMusica VALUES(1, 35);
INSERT INTO EstiloMusica VALUES(1, 36);
INSERT INTO EstiloMusica VALUES(2, 38);
INSERT INTO EstiloMusica VALUES(2, 39);
INSERT INTO EstiloMusica VALUES(2, 40);
INSERT INTO EstiloMusica VALUES(2, 41);
INSERT INTO EstiloMusica VALUES(2, 42);
INSERT INTO EstiloMusica VALUES(2, 43);
INSERT INTO EstiloMusica VALUES(2, 44);
INSERT INTO EstiloMusica VALUES(2, 45);
INSERT INTO EstiloMusica VALUES(2, 46);
INSERT INTO EstiloMusica VALUES(2, 47);
INSERT INTO EstiloMusica VALUES(2, 48);
INSERT INTO EstiloMusica VALUES(2, 49);
INSERT INTO EstiloMusica VALUES(2, 50);
INSERT INTO EstiloMusica VALUES(2, 51);
INSERT INTO EstiloMusica VALUES(2, 52);
INSERT INTO EstiloMusica VALUES(2, 53);
INSERT INTO EstiloMusica VALUES(2, 54);
INSERT INTO EstiloMusica VALUES(2, 55);
INSERT INTO EstiloMusica VALUES(2, 56);
INSERT INTO EstiloMusica VALUES(2, 57);
INSERT INTO EstiloMusica VALUES(2, 58);
INSERT INTO EstiloMusica VALUES(2, 59);
INSERT INTO EstiloMusica VALUES(2, 60);
INSERT INTO EstiloMusica VALUES(2, 61);
INSERT INTO EstiloMusica VALUES(2, 62);
INSERT INTO EstiloMusica VALUES(2, 63);
INSERT INTO EstiloMusica VALUES(2, 64);
INSERT INTO EstiloMusica VALUES(2, 65);
INSERT INTO EstiloMusica VALUES(2, 66);
INSERT INTO EstiloMusica VALUES(2, 67);
INSERT INTO EstiloMusica VALUES(2, 68);
INSERT INTO EstiloMusica VALUES(3, 69);
INSERT INTO EstiloMusica VALUES(3, 70);
INSERT INTO EstiloMusica VALUES(3, 71);
INSERT INTO EstiloMusica VALUES(3, 72);
INSERT INTO EstiloMusica VALUES(3, 73);
INSERT INTO EstiloMusica VALUES(3, 74);
INSERT INTO EstiloMusica VALUES(3, 75);
INSERT INTO EstiloMusica VALUES(3, 76);
INSERT INTO EstiloMusica VALUES(3, 77);
INSERT INTO EstiloMusica VALUES(3, 78);
INSERT INTO EstiloMusica VALUES(3, 79);
INSERT INTO EstiloMusica VALUES(3, 80);
INSERT INTO EstiloMusica VALUES(3, 81);
INSERT INTO EstiloMusica VALUES(3, 82);
INSERT INTO EstiloMusica VALUES(3, 83);
INSERT INTO EstiloMusica VALUES(2, 84);
INSERT INTO EstiloMusica VALUES(3, 84);
INSERT INTO EstiloMusica VALUES(2, 85);
INSERT INTO EstiloMusica VALUES(2, 86);
INSERT INTO EstiloMusica VALUES(2, 87);
INSERT INTO EstiloMusica VALUES(2, 88);
INSERT INTO EstiloMusica VALUES(2, 89);
INSERT INTO EstiloMusica VALUES(2, 90);
INSERT INTO EstiloMusica VALUES(2, 91);
INSERT INTO EstiloMusica VALUES(2, 92);
INSERT INTO EstiloMusica VALUES(2, 93);
INSERT INTO EstiloMusica VALUES(3, 94);
INSERT INTO EstiloMusica VALUES(3, 95);
INSERT INTO EstiloMusica VALUES(2, 95);
INSERT INTO EstiloMusica VALUES(3, 96);
INSERT INTO EstiloMusica VALUES(3, 97);
INSERT INTO EstiloMusica VALUES(3, 98);
INSERT INTO EstiloMusica VALUES(3, 99);
INSERT INTO EstiloMusica VALUES(3, 100);
INSERT INTO EstiloMusica VALUES(3, 101);
INSERT INTO EstiloMusica VALUES(3, 102);
INSERT INTO EstiloMusica VALUES(3, 103);
INSERT INTO EstiloMusica VALUES(3, 104);
INSERT INTO EstiloMusica VALUES(5, 105);
INSERT INTO EstiloMusica VALUES(5, 106);
INSERT INTO EstiloMusica VALUES(5, 107);
INSERT INTO EstiloMusica VALUES(5, 108);
INSERT INTO EstiloMusica VALUES(5, 109);
INSERT INTO EstiloMusica VALUES(5, 110);
INSERT INTO EstiloMusica VALUES(5, 111);
INSERT INTO EstiloMusica VALUES(5, 112);
INSERT INTO EstiloMusica VALUES(5, 113);
INSERT INTO EstiloMusica VALUES(5, 114);
INSERT INTO EstiloMusica VALUES(5, 115);
INSERT INTO EstiloMusica VALUES(5, 116);
INSERT INTO EstiloMusica VALUES(5, 117);
INSERT INTO EstiloMusica VALUES(5, 118);
INSERT INTO EstiloMusica VALUES(5, 119);
INSERT INTO EstiloMusica VALUES(5, 120);
INSERT INTO EstiloMusica VALUES(5, 121);
INSERT INTO EstiloMusica VALUES(5, 122);
INSERT INTO EstiloMusica VALUES(5, 123);
INSERT INTO EstiloMusica VALUES(5, 124);

-- UtilizadorSessao 
INSERT INTO UtilizadorSessao VALUES(1, 1);
INSERT INTO UtilizadorSessao VALUES(2, 2);
INSERT INTO UtilizadorSessao VALUES(2, 4);
INSERT INTO UtilizadorSessao VALUES(3, 3);
INSERT INTO UtilizadorSessao VALUES(1, 4);
INSERT INTO UtilizadorSessao VALUES(1, 5);
INSERT INTO UtilizadorSessao VALUES(1, 3);
INSERT INTO UtilizadorSessao VALUES(4, 6);
INSERT INTO UtilizadorSessao VALUES(4, 2);
INSERT INTO UtilizadorSessao VALUES(5, 4);
INSERT INTO UtilizadorSessao VALUES(6, 3);
INSERT INTO UtilizadorSessao VALUES(6, 4);
INSERT INTO UtilizadorSessao VALUES(7, 5);
INSERT INTO UtilizadorSessao VALUES(8, 6);
INSERT INTO UtilizadorSessao VALUES(8, 7);
INSERT INTO UtilizadorSessao VALUES(9, 6);
INSERT INTO UtilizadorSessao VALUES(10, 2);
INSERT INTO UtilizadorSessao VALUES(11, 7);
INSERT INTO UtilizadorSessao VALUES(11, 10);
INSERT INTO UtilizadorSessao VALUES(12, 21);
INSERT INTO UtilizadorSessao VALUES(13, 13);
INSERT INTO UtilizadorSessao VALUES(14, 28);
INSERT INTO UtilizadorSessao VALUES(15, 13);
INSERT INTO UtilizadorSessao VALUES(16, 14);
INSERT INTO UtilizadorSessao VALUES(16, 23);
INSERT INTO UtilizadorSessao VALUES(16, 24);
INSERT INTO UtilizadorSessao VALUES(16, 25);
INSERT INTO UtilizadorSessao VALUES(17, 26);
INSERT INTO UtilizadorSessao VALUES(17, 27);
INSERT INTO UtilizadorSessao VALUES(18, 28);
INSERT INTO UtilizadorSessao VALUES(19, 29);
INSERT INTO UtilizadorSessao VALUES(20, 11);
INSERT INTO UtilizadorSessao VALUES(21, 14);
INSERT INTO UtilizadorSessao VALUES(21, 13);
INSERT INTO UtilizadorSessao VALUES(22, 14);
INSERT INTO UtilizadorSessao VALUES(23, 15);
INSERT INTO UtilizadorSessao VALUES(24, 23);
INSERT INTO UtilizadorSessao VALUES(30, 1);
INSERT INTO UtilizadorSessao VALUES(30, 2);
INSERT INTO UtilizadorSessao VALUES(30, 4);

-- Pertence 
INSERT INTO Pertence VALUES(1, 1);
INSERT INTO Pertence VALUES(1, 2);
INSERT INTO Pertence VALUES(1, 3);
INSERT INTO Pertence VALUES(1, 4);
INSERT INTO Pertence VALUES(1, 5);
INSERT INTO Pertence VALUES(1, 6);
INSERT INTO Pertence VALUES(1, 7);
INSERT INTO Pertence VALUES(1, 8);
INSERT INTO Pertence VALUES(1, 9);
INSERT INTO Pertence VALUES(1, 10);
INSERT INTO Pertence VALUES(1, 11);
INSERT INTO Pertence VALUES(1, 12);
INSERT INTO Pertence VALUES(2, 15);
INSERT INTO Pertence VALUES(2, 18);
INSERT INTO Pertence VALUES(2, 22);
INSERT INTO Pertence VALUES(2, 23);
INSERT INTO Pertence VALUES(2, 24);
INSERT INTO Pertence VALUES(2, 25);
INSERT INTO Pertence VALUES(3, 28);
INSERT INTO Pertence VALUES(3, 32);

-- Segue 
INSERT INTO Segue VALUES(3, 1);
INSERT INTO Segue VALUES(1, 3);
INSERT INTO Segue VALUES(2, 1);
INSERT INTO Segue VALUES(2, 3);
INSERT INTO Segue VALUES(1, 2);
INSERT INTO Segue VALUES(4, 1);
INSERT INTO Segue VALUES(5, 1);
INSERT INTO Segue VALUES(6, 1);
INSERT INTO Segue VALUES(7, 2);
INSERT INTO Segue VALUES(8, 2);
INSERT INTO Segue VALUES(9, 2);
INSERT INTO Segue VALUES(10, 1);
INSERT INTO Segue VALUES(10, 4);
INSERT INTO Segue VALUES(11, 6);
INSERT INTO Segue VALUES(12, 8);
INSERT INTO Segue VALUES(13, 10);
INSERT INTO Segue VALUES(14, 12);
INSERT INTO Segue VALUES(15, 14);
INSERT INTO Segue VALUES(16, 16);
INSERT INTO Segue VALUES(17, 18);
INSERT INTO Segue VALUES(18, 20);
INSERT INTO Segue VALUES(19, 22);
INSERT INTO Segue VALUES(20, 24);
INSERT INTO Segue VALUES(21, 26);
INSERT INTO Segue VALUES(22, 30);
INSERT INTO Segue VALUES(23, 30);
INSERT INTO Segue VALUES(25, 1);
INSERT INTO Segue VALUES(26, 2);
INSERT INTO Segue VALUES(27, 26);
INSERT INTO Segue VALUES(27, 30);
INSERT INTO Segue VALUES(28, 30);
INSERT INTO Segue VALUES(30, 2);
INSERT INTO Segue VALUES(30, 1);
INSERT INTO Segue VALUES(30, 3);

